# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f364a0c9b0b1fe954e988f396f5344699b85d98201c0d32e676929bfa405fdf85a7e799d564805ab98efbd2711caa5760bc735d12361f84f8f75b841b8bb269

test:
  secret_key_base: edb4d468f3b20fff93b60ff8b0ec1ece82f3a0387fe34a8dfd0f7c8c39f569f52e057b1fc52fdafcaccbced325bfe6c13dbffe3f78909a31fdba9a5a4dbec144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
